name: ci
on: 
  push:
  pull_request:

jobs:
  test:
    runs-on: windows-latest   # Máquina virtual Windows

    strategy:
      matrix:
        python-version: ['3.13']

    steps:
      # 1. Descargar el código del repo
      - uses: actions/checkout@v4

      # 2. Instalar Python en Windows
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Actualizar pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # 4. Instalar dependencias (ajusta si usas Poetry/Conda)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      # 5. Revisar calidad con Ruff, Black e isort
      - name: Run Ruff
        run: ruff check .

      - name: Run Black
        run: black --check .

      - name: Run isort
        run: isort --check-only .

      # 6. Ejecutar tests con pytest
      - name: Run tests
        run: pytest -q --maxfail=1 --disable-warnings
